name: Telegram Admin Bot CI/CD

on:
  push:
    branches:
      - master
#  pull_request:
#    branches:
#      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - uses: dschep/install-pipenv-action@v1
      - name: Install requirements
        run: pipenv install
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t tg-admin-bot .
      - name: Tags
        run: |
          docker tag tg-admin-bot ${{ secrets.DOCKER_USER }}/tg-admin-bot:${{ github.sha }}
          docker tag tg-admin-bot ${{ secrets.DOCKER_USER }}/tg-admin-bot:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/tg-admin-bot:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/tg-admin-bot:latest
